// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package queries

import (
	"database/sql"

	"github.com/sqlc-dev/pqtype"
)

type CheckpointTx struct {
	Txid                 string
	Tx                   string
	CommitmentTxid       string
	IsRootCommitmentTxid bool
	OffchainTxid         string
}

type Intent struct {
	ID      sql.NullString
	RoundID sql.NullString
	Proof   sql.NullString
	Message sql.NullString
}

type IntentWithInputsVw struct {
	Txid           sql.NullString
	Vout           sql.NullInt32
	Pubkey         sql.NullString
	Amount         sql.NullInt64
	ExpiresAt      sql.NullInt64
	CreatedAt      sql.NullInt64
	CommitmentTxid sql.NullString
	SpentBy        sql.NullString
	Spent          sql.NullBool
	Unrolled       sql.NullBool
	Swept          sql.NullBool
	Preconfirmed   sql.NullBool
	SettledBy      sql.NullString
	ArkTxid        sql.NullString
	IntentID       sql.NullString
	Commitments    []byte
	ID             sql.NullString
	RoundID        sql.NullString
	Proof          sql.NullString
	Message        sql.NullString
}

type IntentWithReceiversVw struct {
	IntentID       sql.NullString
	Pubkey         sql.NullString
	OnchainAddress sql.NullString
	Amount         sql.NullInt64
	ID             sql.NullString
	RoundID        sql.NullString
	Proof          sql.NullString
	Message        sql.NullString
}

type MarketHour struct {
	ID            int32
	StartTime     int64
	EndTime       int64
	Period        int64
	RoundInterval int64
	UpdatedAt     int64
}

type OffchainTx struct {
	Txid              string
	Tx                string
	StartingTimestamp int64
	EndingTimestamp   int64
	ExpiryTimestamp   int64
	FailReason        sql.NullString
	StageCode         int32
}

type OffchainTxVw struct {
	Txid                 string
	Tx                   string
	StartingTimestamp    int64
	EndingTimestamp      int64
	ExpiryTimestamp      int64
	FailReason           sql.NullString
	StageCode            int32
	CheckpointTxid       sql.NullString
	CheckpointTx         sql.NullString
	CommitmentTxid       sql.NullString
	IsRootCommitmentTxid sql.NullBool
	OffchainTxid         sql.NullString
}

type Receiver struct {
	IntentID       string
	Pubkey         string
	OnchainAddress string
	Amount         int64
}

type Round struct {
	ID                 string
	StartingTimestamp  int64
	EndingTimestamp    int64
	Ended              bool
	Failed             bool
	StageCode          int32
	ConnectorAddress   string
	Version            int32
	Swept              bool
	VtxoTreeExpiration int64
	FailReason         sql.NullString
}

type RoundIntentsVw struct {
	ID      sql.NullString
	RoundID sql.NullString
	Proof   sql.NullString
	Message sql.NullString
}

type RoundTxsVw struct {
	Txid     sql.NullString
	Tx       sql.NullString
	RoundID  sql.NullString
	Type     sql.NullString
	Position sql.NullInt32
	Children pqtype.NullRawMessage
}

type RoundWithCommitmentTxVw struct {
	ID                 string
	StartingTimestamp  int64
	EndingTimestamp    int64
	Ended              bool
	Failed             bool
	StageCode          int32
	ConnectorAddress   string
	Version            int32
	Swept              bool
	VtxoTreeExpiration int64
	FailReason         sql.NullString
	Txid               string
	Tx                 string
	RoundID            string
	Type               string
	Position           int32
	Children           pqtype.NullRawMessage
}

type Tx struct {
	Txid     string
	Tx       string
	RoundID  string
	Type     string
	Position int32
	Children pqtype.NullRawMessage
}

type Vtxo struct {
	Txid           string
	Vout           int32
	Pubkey         string
	Amount         int64
	ExpiresAt      int64
	CreatedAt      int64
	CommitmentTxid string
	SpentBy        sql.NullString
	Spent          bool
	Unrolled       bool
	Swept          bool
	Preconfirmed   bool
	SettledBy      sql.NullString
	ArkTxid        sql.NullString
	IntentID       sql.NullString
}

type VtxoCommitmentTxid struct {
	VtxoTxid       string
	VtxoVout       int32
	CommitmentTxid string
}

type VtxoVw struct {
	Txid           string
	Vout           int32
	Pubkey         string
	Amount         int64
	ExpiresAt      int64
	CreatedAt      int64
	CommitmentTxid string
	SpentBy        sql.NullString
	Spent          bool
	Unrolled       bool
	Swept          bool
	Preconfirmed   bool
	SettledBy      sql.NullString
	ArkTxid        sql.NullString
	IntentID       sql.NullString
	Commitments    []byte
}
