version: "2"
sql:
  - engine: "sqlite"
    queries: "sqlc/query.sql"
    schema: "migration"
    gen:
      go:
        package: "queries"
        out: "sqlc/queries"
        overrides:
          - column: "round_intents_vw.id"
            go_type: "database/sql.NullString"
          - column: "round_intents_vw.round_id"
            go_type: "database/sql.NullString"
          - column: "round_intents_vw.proof"
            go_type: "database/sql.NullString"
          - column: "round_intents_vw.message"
            go_type: "database/sql.NullString"

          - column: "intent_with_receivers_vw.id"
            go_type: "database/sql.NullString"
          - column: "intent_with_receivers_vw.round_id"
            go_type: "database/sql.NullString"
          - column: "intent_with_receivers_vw.proof"
            go_type: "database/sql.NullString"
          - column: "intent_with_receivers_vw.message"
            go_type: "database/sql.NullString"

          - column: "intent_with_inputs_vw.id"
            go_type: "database/sql.NullString"
          - column: "intent_with_inputs_vw.round_id"
            go_type: "database/sql.NullString"
          - column: "intent_with_inputs_vw.proof"
            go_type: "database/sql.NullString"
          - column: "intent_with_inputs_vw.message"
            go_type: "database/sql.NullString"

          - column: "intent.id"
            go_type: "database/sql.NullString"
          - column: "intent.round_id"
            go_type: "database/sql.NullString"
          - column: "intent.proof"
            go_type: "database/sql.NullString"
          - column: "intent.message"
            go_type: "database/sql.NullString"