// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package queries

import (
	"database/sql"
)

type CheckpointTx struct {
	Txid               string
	Tx                 string
	CommitmentTxid     string
	IsRootCommitmentTx bool
	VirtualTxid        string
}

type MarketHour struct {
	ID            int64
	StartTime     int64
	EndTime       int64
	Period        int64
	RoundInterval int64
	UpdatedAt     int64
}

type Receiver struct {
	RequestID      string
	Pubkey         sql.NullString
	OnchainAddress sql.NullString
	Amount         int64
}

type RequestReceiverVw struct {
	RequestID      sql.NullString
	Pubkey         sql.NullString
	OnchainAddress sql.NullString
	Amount         sql.NullInt64
	ID             sql.NullString
	RoundID        sql.NullString
	Proof          sql.NullString
	Message        sql.NullString
}

type RequestVtxoVw struct {
	Txid         sql.NullString
	Vout         sql.NullInt64
	Pubkey       sql.NullString
	Amount       sql.NullInt64
	RoundTx      sql.NullString
	SpentBy      sql.NullString
	Spent        sql.NullBool
	Redeemed     sql.NullBool
	Swept        sql.NullBool
	ExpireAt     sql.NullInt64
	CreatedAt    sql.NullInt64
	RequestID    sql.NullString
	SettledBy    sql.NullString
	Preconfirmed sql.NullBool
	ArkTxid      sql.NullString
	Commitments  interface{}
	ID           sql.NullString
	RoundID      sql.NullString
	Proof        sql.NullString
	Message      sql.NullString
}

type Round struct {
	ID                 string
	StartingTimestamp  int64
	EndingTimestamp    int64
	Ended              bool
	Failed             bool
	StageCode          int64
	Txid               string
	ConnectorAddress   string
	Version            int64
	Swept              bool
	VtxoTreeExpiration int64
}

type RoundRequestVw struct {
	ID      sql.NullString
	RoundID sql.NullString
	Proof   sql.NullString
	Message sql.NullString
}

type RoundTxVw struct {
	Txid     sql.NullString
	Tx       sql.NullString
	RoundID  sql.NullString
	Type     sql.NullString
	Position sql.NullInt64
	Children sql.NullString
}

type Tx struct {
	Txid     string
	Tx       string
	RoundID  string
	Type     string
	Position int64
	Children sql.NullString
}

type TxRequest struct {
	ID      sql.NullString
	RoundID sql.NullString
	Proof   sql.NullString
	Message sql.NullString
}

type VirtualTx struct {
	Txid              string
	Tx                string
	StartingTimestamp int64
	EndingTimestamp   int64
	ExpiryTimestamp   int64
	FailReason        sql.NullString
	StageCode         int64
}

type VirtualTxCheckpointTxVw struct {
	Txid               string
	Tx                 string
	StartingTimestamp  int64
	EndingTimestamp    int64
	ExpiryTimestamp    int64
	FailReason         sql.NullString
	StageCode          int64
	CheckpointTxid     string
	CheckpointTx       string
	CommitmentTxid     string
	IsRootCommitmentTx bool
	VirtualTxid        string
}

type Vtxo struct {
	Txid         string
	Vout         int64
	Pubkey       string
	Amount       int64
	RoundTx      string
	SpentBy      string
	Spent        bool
	Redeemed     bool
	Swept        bool
	ExpireAt     int64
	CreatedAt    int64
	RequestID    sql.NullString
	SettledBy    sql.NullString
	Preconfirmed bool
	ArkTxid      sql.NullString
}

type VtxoCommitmentTxid struct {
	VtxoTxid       string
	VtxoVout       int64
	CommitmentTxid string
}

type VtxoVw struct {
	Txid         string
	Vout         int64
	Pubkey       string
	Amount       int64
	RoundTx      string
	SpentBy      string
	Spent        bool
	Redeemed     bool
	Swept        bool
	ExpireAt     int64
	CreatedAt    int64
	RequestID    sql.NullString
	SettledBy    sql.NullString
	Preconfirmed bool
	ArkTxid      sql.NullString
	Commitments  interface{}
}
