// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1GetBatchSweepTransactionsResponse v1 get batch sweep transactions response
//
// swagger:model v1GetBatchSweepTransactionsResponse
type V1GetBatchSweepTransactionsResponse struct {

	// swept by
	SweptBy []string `json:"sweptBy"`
}

// Validate validates this v1 get batch sweep transactions response
func (m *V1GetBatchSweepTransactionsResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this v1 get batch sweep transactions response based on context it is used
func (m *V1GetBatchSweepTransactionsResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1GetBatchSweepTransactionsResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1GetBatchSweepTransactionsResponse) UnmarshalBinary(b []byte) error {
	var res V1GetBatchSweepTransactionsResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
