// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package queries

import (
	"database/sql"

	"github.com/sqlc-dev/pqtype"
)

type CheckpointTx struct {
	Txid                 string
	Tx                   string
	CommitmentTxid       string
	IsRootCommitmentTxid bool
	VirtualTxid          string
}

type MarketHour struct {
	ID            int32
	StartTime     int64
	EndTime       int64
	Period        int64
	RoundInterval int64
	UpdatedAt     int64
}

type Receiver struct {
	RequestID      string
	Pubkey         string
	OnchainAddress string
	Amount         int64
}

type RequestReceiverVw struct {
	RequestID      sql.NullString
	Pubkey         sql.NullString
	OnchainAddress sql.NullString
	Amount         sql.NullInt64
	ID             sql.NullString
	RoundID        sql.NullString
	Proof          sql.NullString
	Message        sql.NullString
}

type RequestVtxoVw struct {
	Txid           sql.NullString
	Vout           sql.NullInt32
	Pubkey         sql.NullString
	Amount         sql.NullInt64
	CommitmentTxid sql.NullString
	Spent          sql.NullBool
	Redeemed       sql.NullBool
	Swept          sql.NullBool
	ExpireAt       sql.NullInt64
	CreatedAt      sql.NullInt64
	RequestID      sql.NullString
	SettledBy      sql.NullString
	ArkTxid        sql.NullString
	Preconfirmed   sql.NullBool
	SpentBy        sql.NullString
	Commitments    []byte
	ID             sql.NullString
	RoundID        sql.NullString
	Proof          sql.NullString
	Message        sql.NullString
}

type Round struct {
	ID                 string
	StartingTimestamp  int64
	EndingTimestamp    int64
	Ended              bool
	Failed             bool
	StageCode          int32
	ConnectorAddress   string
	Version            int32
	Swept              bool
	VtxoTreeExpiration int64
}

type RoundCommitmentTxVw struct {
	ID                 string
	StartingTimestamp  int64
	EndingTimestamp    int64
	Ended              bool
	Failed             bool
	StageCode          int32
	ConnectorAddress   string
	Version            int32
	Swept              bool
	VtxoTreeExpiration int64
	Txid               string
	Tx                 string
	RoundID            string
	Type               string
	Position           int32
	Children           pqtype.NullRawMessage
}

type RoundRequestVw struct {
	ID      sql.NullString
	RoundID sql.NullString
	Proof   sql.NullString
	Message sql.NullString
}

type RoundTxVw struct {
	Txid     sql.NullString
	Tx       sql.NullString
	RoundID  sql.NullString
	Type     sql.NullString
	Position sql.NullInt32
	Children pqtype.NullRawMessage
}

type Tx struct {
	Txid     string
	Tx       string
	RoundID  string
	Type     string
	Position int32
	Children pqtype.NullRawMessage
}

type TxRequest struct {
	ID      sql.NullString
	RoundID sql.NullString
	Proof   sql.NullString
	Message sql.NullString
}

type VirtualTx struct {
	Txid              string
	Tx                string
	StartingTimestamp int64
	EndingTimestamp   int64
	ExpiryTimestamp   int64
	FailReason        sql.NullString
	StageCode         int32
}

type VirtualTxCheckpointTxVw struct {
	Txid                 string
	Tx                   string
	StartingTimestamp    int64
	EndingTimestamp      int64
	ExpiryTimestamp      int64
	FailReason           sql.NullString
	StageCode            int32
	CheckpointTxid       sql.NullString
	CheckpointTx         sql.NullString
	CommitmentTxid       sql.NullString
	IsRootCommitmentTxid sql.NullBool
	VirtualTxid          sql.NullString
}

type Vtxo struct {
	Txid           string
	Vout           int32
	Pubkey         string
	Amount         int64
	CommitmentTxid string
	Spent          bool
	Redeemed       bool
	Swept          bool
	ExpireAt       int64
	CreatedAt      int64
	RequestID      sql.NullString
	SettledBy      sql.NullString
	ArkTxid        sql.NullString
	Preconfirmed   bool
	SpentBy        sql.NullString
}

type VtxoCommitmentTxid struct {
	VtxoTxid       string
	VtxoVout       int32
	CommitmentTxid string
}

type VtxoVw struct {
	Txid           string
	Vout           int32
	Pubkey         string
	Amount         int64
	CommitmentTxid string
	Spent          bool
	Redeemed       bool
	Swept          bool
	ExpireAt       int64
	CreatedAt      int64
	RequestID      sql.NullString
	SettledBy      sql.NullString
	ArkTxid        sql.NullString
	Preconfirmed   bool
	SpentBy        sql.NullString
	Commitments    []byte
}
